name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - requests=2.24.0
  - pip=23.3.1
  - urllib3=1.24.1
  - scikit-learn=0.24.1
  - matplotlib==3.2.2
  - plotly==4.4.1
  - pillow=8.1.2
  - mlflow=1.14.1
  - numpy=1.19.2
  - pip:
      - wandb==0.16.0
      - omegaconf==2.0.6
