name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - requests=2.24.0
  - pip=23.3.1
  - urllib3=1.24.1
  - mlflow=1.14.1
  - hydra-core=1.0.6
  - numpy=1.19.2
  - pip:
      - wandb==0.16.0
      - hydra-joblib-launcher==1.1.2
