name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - requests=2.24.0
  - pip=23.3.1
  - urllib3=1.24.1
  - pytest=6.2.2
  - scipy=1.6.1
  - pip:
      - wandb==0.16.0