name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.2.3
  - scikit-learn=0.24.1
  - requests=2.24.0
  - pip=23.3.1
  - urllib3=1.24.1
  - numpy=1.19.2
  - pip:
      - wandb==0.16.0